### ISSUE TITLE
Does not build in SBCL

### ISSUE THREAD

**Issue by quicklisp** [jschatzer/clim-widgets#2]
http://report.quicklisp.org/2015-05-29/failure-report/clim-widgets.html#clim-widgets has a log. I don't really understand the error, sorry.

**Comment by quicklisp** [comment]
Got this feedback from #sbcl:

```
17:13 <|3b|> Xach: looks like clim-widgets bug, it uses #~ reader from 
      lol-syntax readrable rather than the one it defines
```

**Comment by jschatzer** [comment]
Now it should be ok, 
thank you

-- 
Johann  Schatzer


Zach Beane <notifications@github.com>:
