### ISSUE TITLE
Does not build - reference to INTERNALS::*XPM-X11-COLORS*

### ISSUE THREAD

**Issue by quicklisp** [jschatzer/clim-widgets#3]
CLIM-INTERNALS::*XPM-X11-COLORS* no longer exists.

**Comment by gas2serra** [comment]
Do you mean CLIM-INTERNALS::*XPM-X11-COLORS*?
I'm going to put it back. 

Are there other symbols missing?

**Comment by quicklisp** [comment]
Nothing that I've seen so far, but that error stops the build so it's possible fixing it will expose more problems.

**Comment by gas2serra** [comment]
The xpm library has been moved in another package. I submit a patch to mcclim to import XPM-X11-COLORS into climi package.

**Comment by gas2serra** [comment]
The patch has been merged into the master branch of mcclim.

**Comment by quicklisp** [comment]
Looks good to me, thanks!
